import "../../public/css/globals.css";
import "../../public/fonts/font.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Cookie from "@/component/Cookie";
import TopButton from "@/component/TopButton";
import CommingSoon from "@/component/CommingSoon";

export const metadata = {
  title: "REIG",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "../public/img/REG.svg",
        href: "../public/img/REG.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg" href="../public/img/REG.svg" />
      </head>
      <body>
        {/* <Header />
        <main>{children}</main>
        <SpeedInsights />
        <Cookie />
        <TopButton />
        <Footer /> */}
        <CommingSoon/>
      </body>
    </html>
  );
}
